// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { offlineFetch } from '@/lib/offlineSync';

// These are public client identifiers, not privileged secrets. Lovable does not
// inject Vite variables into every production build, so keep safe public
// fallbacks while still allowing each environment to override them.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://bvmadmmeheyclurvgrju.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
  || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2bWFkbW1laGV5Y2x1cnZncmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyNTI2MzksImV4cCI6MjA4MzgyODYzOX0.aQEzElYr-IPLTExzGYrQJdx52XM6L0dP-ekB3AMl-m8';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Using createClient without Database type since the schema is not yet defined
// This allows all table queries to work without type errors
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  global: {
    fetch: offlineFetch,
  },
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
